[package]
name = "rust-markdown-studio"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = { version = "0.21", features = ["csr"] }
pulldown-cmark = "0.10.0"
gloo-storage = "0.3.0"
web-sys = { version = "0.3.69", features = ["HtmlTextAreaElement"] }
